name: lsst_lsb
channels:
  - conda-forge
  - defaults
dependencies:
  - asdf=5.0.0
  - asdf-astropy=0.6.1
  - asdf-coordinates-schemas=0.4.0
  - asdf-standard=1.4.0
  - asdf-transform-schemas=0.6.0
  - asdf-wcs-schemas=0.5.0
  - astropy=5.1
  - h5py=3.14.0
  - hdf4=4.2.13
  - hdf5=1.14.5
  - ipykernel=6.29.5
  - ipympl=0.9.7
  - ipython=9.1.0
  - ipython_genutils=0.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.0.4
  - jupyter=1.1.1
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_fileid=0.9.3
  - jupyter_server_terminals=0.5.3
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.5
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nbclassic=1.3.1
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - photutils=1.13.0
  - pillow=11.3.0
  - python=3.11.5
  - scikit-image=0.25.2
  - scipy=1.16.2
  - tqdm=4.67.1
  - widgetsnbextension=4.0.13
prefix: /home/garreth/miniconda3/envs/lsst_lsb
