name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=23.1.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - conda=4.11.0
  - conda-package-handling=1.6.1
  - cryptography=43.0.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cython=3.0.11
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - emcee=3.1.6
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.6.4
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.6.0
  - hdf5=1.10.6
  - icu=73.1
  - idna=3.7
  - importlib_resources=6.4.0
  - intel-openmp=2021.4.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=7.4.9
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.11.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.5
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mysql=8.4.0
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=6.1.3
  - numexpr=2.8.4
  - numpy-base=1.24.3
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.17
  - pandas=1.3.4
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycosat=0.6.6
  - pycparser=2.21
  - pyerfa=2.0.0
  - pygments=2.15.1
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.16.2
  - python_abi=3.8
  - pytz=2024.1
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - readline=8.2
  - referencing=0.30.2
  - requests=2.32.3
  - rpds-py=0.10.6
  - ruamel_yaml=0.15.87
  - send2trash=1.8.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - terminado=0.17.1
  - testpath=0.6.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.1.7
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
    - anyio==4.5.2
    - arrow==1.3.0
    - asciitree==0.3.3
    - astropy==5.2.2
    - astropy-healpix==0.7
    - async-lru==2.0.4
    - babel==2.17.0
    - beautifulsoup4==4.13.5
    - click==8.1.8
    - cloudpickle==3.1.1
    - dask==2023.5.0
    - distro==1.6.0
    - exceptiongroup==1.3.0
    - fast-histogram==0.12
    - fasteners==0.19
    - fqdn==1.5.1
    - fsspec==2025.3.0
    - future==0.18.2
    - h11==0.16.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - imageio==2.33.0
    - importlib-metadata==8.5.0
    - ipywidgets==8.1.7
    - isoduration==20.11.0
    - joblib==1.3.2
    - json5==0.12.1
    - jsonpointer==3.0.0
    - jupyter==1.1.1
    - jupyter-console==6.6.3
    - jupyter-events==0.10.0
    - jupyter-lsp==2.3.0
    - jupyter-server==2.14.2
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.8
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - jupyterlab-widgets==3.0.15
    - lazy-loader==0.3
    - locket==1.0.0
    - lsstdesc-coord==1.2.1
    - mistune==3.1.4
    - nbclient==0.10.1
    - nbconvert==7.16.6
    - networkx==3.1
    - notebook-shim==0.2.4
    - numcodecs==0.12.1
    - numpy==1.24.4
    - overrides==7.7.0
    - packaging==23.2
    - partd==1.4.1
    - pillow==10.1.0
    - python-json-logger==3.3.0
    - pywavelets==1.4.1
    - pyyaml==5.4.1
    - reproject==0.13.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - sniffio==1.3.1
    - soupsieve==2.7
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - toolz==1.0.0
    - types-python-dateutil==2.9.0.20241206
    - uri-template==1.3.0
    - webcolors==24.8.0
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.14
    - zarr==2.16.1
    - zipp==3.20.2
prefix: /home/garreth/miniconda3
