name: lsst_lsb
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - affine=2.4.0
  - aiofiles=22.1.0
  - aiosqlite=0.21.0
  - anyio=4.10.0
  - aom=3.6.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asdf=5.0.0
  - asdf-astropy=0.6.1
  - asdf-coordinates-schemas=0.4.0
  - asdf-standard=1.4.0
  - asdf-transform-schemas=0.6.0
  - asdf-wcs-schemas=0.5.0
  - astropy=5.1
  - asttokens=3.0.0
  - attrs=24.3.0
  - babel=2.16.0
  - beautifulsoup4=4.13.5
  - blas=1.0
  - bleach=6.2.0
  - blosc=1.21.6
  - boost-cpp=1.82.0
  - bottleneck=1.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.3.0
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=2.2.1
  - expat=2.7.1
  - fontconfig=2.15.0
  - fonttools=4.59.2
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.10
  - geos=3.10.6
  - geotiff=1.7.0
  - giflib=5.2.2
  - graphite2=1.3.14
  - gwcs=0.18.3
  - h5py=3.14.0
  - harfbuzz=10.2.0
  - hdf4=4.2.13
  - hdf5=1.14.5
  - icu=73.1
  - idna=3.7
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - intel-openmp=2025.0.0
  - ipykernel=6.29.5
  - ipympl=0.9.7
  - ipython=9.1.0
  - ipython_genutils=0.2.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.0.4
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - jpeg=9f
  - json-c=0.16
  - json5=0.9.25
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_fileid=0.9.3
  - jupyter_server_terminals=0.5.3
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.5
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jxrlib=1.2
  - kealib=1.5.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libaec=1.1.3
  - libavif=1.1.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcups=2.4.2
  - libcurl=8.4.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgdal=3.6.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libnetcdf=4.8.1
  - libnghttp2=1.57.0
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mesalib=25.1.5
  - minizip=4.0.3
  - mistune=3.1.2
  - mkl=2025.0.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpi=1.0
  - mpi4py=4.0.3
  - mpich=4.1.1
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nbclassic=1.3.1
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - nspr=4.37
  - nss=3.117
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.4
  - overrides=7.4.0
  - packaging=25.0
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - photutils=1.13.0
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - poppler=24.09.0
  - poppler-data=0.4.12
  - proj=9.3.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pyerfa=2.0.1.5
  - pygments=2.19.1
  - pyparsing=3.0.9
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python_abi=3.11
  - pyyaml=6.0.2
  - pyzmq=24.0.1
  - qhull=2020.2
  - qtbase=6.9.2
  - qtconsole=5.7.0
  - qtdeclarative=6.9.2
  - qtpy=2.4.3
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - rasterio=1.4.3
  - readline=8.3
  - referencing=0.30.2
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.22.3
  - scikit-image=0.25.2
  - scipy=1.16.2
  - semantic_version=2.10.0
  - send2trash=1.8.2
  - setuptools=78.1.1
  - shapely=2.1.1
  - sip=6.12.0
  - six=1.17.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - terminado=0.18.1
  - tifffile=2024.12.12
  - tiledb=2.3.3
  - tinycss2=1.4.0
  - tk=8.6.15
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=15.1.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.4
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - y-py=0.6.2
  - yaml=0.2.5
  - ypy-websocket=0.8.4
  - zeromq=4.3.5
  - zfp=1.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstd=1.5.7
prefix: /home/garreth/miniconda3/envs/lsst_lsb
